version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

  build-docker:
    machine:
      image: ubuntu-2404:current
    steps:
      - checkout
      - run:
          name: Build Docker image
          command: |
            docker build -t node-js-sample .
      - run:
          name: Save Docker image
          command: |
            docker save node-js-sample | gzip > node-js-sample.tar.gz
      - persist_to_workspace:
          root: .
          paths:
            - node-js-sample.tar.gz

  publish-docker:
    machine:
      image: ubuntu-2404:current
    steps:
      - checkout
      - attach_workspace:
          at: /workspace
      - run:
          name: Load Docker image
          command: |
            docker load < /workspace/node-js-sample.tar.gz
      - run:
          name: Login to Docker Hub
          command: |
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
      - run:
          name: Publish Docker image
          command: |
            docker tag node-js-sample $DOCKERHUB_USERNAME/node-js-sample:latest
            docker push $DOCKERHUB_USERNAME/node-js-sample:latest

workflows:
  docker-workflow:
    jobs:
      - say-hello
      - build-docker
      - publish-docker:
          requires:
            - build-docker